### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Oleg-Sob** [Hagakurje/ESPHome_Gree_AC#11]
When compiling, it gives an error:
/config/esphome/ir-remote.yaml:45:34: error: expected type-specifier before 'GreeAC'
/config/esphome/ir-remote.yaml:48:25: error: could not convert '{bedroom_ac}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::climate::Climate*>'

**Comment by Hagakurje** [comment]
I think your jaml file is not valid

**Comment by Oleg-Sob** [comment]
I'm sorry, everything worked out, I made a mistake. Now everything works.

**Comment by Oleg-Sob** [comment]
Everything is working . Topic closed.
