### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Valerich1971** [Hagakurje/ESPHome_Gree_AC#3]
hi, is it possible to add to the firmware the ability to receive and read commands from the remote control of the air conditioner as a feedback

**Comment by Hagakurje** [comment]
Hi. In theory it is possible, but I don't know how.

**Comment by drthanwho** [comment]
The IR Climate Component in ESPHOME has that ability for those set of A/Cs listed there. But I don't know enough to work that out 
https://esphome.io/components/climate/ir_climate.html?highlight=ir
