### ISSUE TITLE
Add support for AWAY mode

### ISSUE THREAD

**Issue by nagyrobi** [Hagakurje/ESPHome_Gree_AC#6]
Would it be possible to add support for AWAY mode in the lambdas? (https://esphome.io/components/climate/index.html)
The goal would be to have a preconfigured temperature for AWAY mode (in esphome node's yaml config), and use HA's service system to switch this mode on or off (it's a boolean in esphome) based on presence detection or similar.

In reality it would just set the target temp to this predefined value in AWAY mode, and restore to what it was before when not.

**Comment by Hagakurje** [comment]
Hi. It is possible in general, I think, but I will not do this. Why? Because is just stupid device, it must only call AC, and for automation you have Home Assistant. Just create automation for store previous params and call service for set temp, hvac, fan, etc.
