### ISSUE TITLE
unsupported model? 

### ISSUE THREAD

**Issue by tiimsvk** [Hagakurje/ESPHome_Gree_AC#7]
Hi, I have a Fisher air conditioner
Both Xiaomi and Tuya blaster recognized it as Gree

the remote control is model YAN1F6
the air conditioner has the designation FSAI-SU-124BE3

But after setting it according to the instructions on the website, the air conditioner does not respond.

Is it some other unsupported model?
Thanks

**Comment by Hagakurje** [comment]
Hi, I don't have Fisher ac, so I don't know, is it supported. What ir remote device are you using - Avatto S06 or other?
